---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
